#!/bin/bash

#
# Usage:     
# $0 profile_name access_key_id secret_access_key session_token
#

if [ "$AWS_SHARED_CREDENTIALS_FILE" != "" ]; then
    CREDENTIAL_FILE="$AWS_SHARED_CREDENTIALS_FILE"
else
    CREDENTIAL_FILE="$HOME/.aws/credentials"
fi

[[ "$#" -lt 4 ]] && exit 1

TARGET_PROFILE="$1" && shift
ACCESS_KEY_ID="$1" && shift
SECRET_ACCESS_KEY="$1" && shift
SESSION_TOKEN="$1" && shift

NEW_CREDENTIALS="[$TARGET_PROFILE]\naws_access_key_id = $ACCESS_KEY_ID\naws_secret_access_key = $SECRET_ACCESS_KEY\naws_session_token = $SESSION_TOKEN"

if [ "$(grep "^\[$TARGET_PROFILE\]$" $CREDENTIAL_FILE)" != "" ]; then

  sed -i -e "/^\[$TARGET_PROFILE\]$/ {
    N; /\n.*$/ { 
      N; /\n.*$/ { 
        N; /\n.*$/ { 
          s/^.*\n.*\n.*\n.*$/$( echo $NEW_CREDENTIALS | sed 's/\//\\\//g' )/m
        }
      }
    }
  }" $CREDENTIAL_FILE

else

  [[ "$( tail -1 $CREDENTIAL_FILE )" != "\n" ]] && echo -e "" >> $CREDENTIAL_FILE

  echo -e $NEW_CREDENTIALS >> $CREDENTIAL_FILE

fi

[[ "$1" = "--print" ]] && echo -e $NEW_CREDENTIALS | tail -3

exit 0