#!/bin/bash

#
# Usage:     
# $0 profile_from profile_to role_arn [session_name]
#

[[ "$#" -lt 3 ]] && exit 1

PROFILE_FROM="$1" && shift
PROFILE_TO="$1" && shift
ROLE_ARN="$1" && shift

if [[ "$1" =~ ^[-=,.@a-zA-Z0-9]{1,}$ ]] && ! [[ "$1" =~ ^--[-a-zA-Z]{1,}$ ]]; then
  SESSION_NAME="$1" && shift
else
  SESSION_NAME="$( cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 )"
fi

JSON_RESPONSE="$( aws --profile $PROFILE_FROM sts assume-role --role-arn $ROLE_ARN --role-session-name $SESSION_NAME )"

[[ "$JSON_RESPONSE" == "" ]] && echo "" && exit 1

ACCESS_KEY_ID="$( sed -e 's/^"//' -e 's/"$//' <<< "$( echo $JSON_RESPONSE | jq .Credentials.AccessKeyId )" )"
SECRET_ACCESS_KEY="$( sed -e 's/^"//' -e 's/"$//' <<< "$( echo $JSON_RESPONSE | jq .Credentials.SecretAccessKey )" )"
SESSION_TOKEN="$( sed -e 's/^"//' -e 's/"$//' <<< "$( echo $JSON_RESPONSE | jq .Credentials.SessionToken )" )"

$HOME/bin/aws-profile $PROFILE_TO $ACCESS_KEY_ID $SECRET_ACCESS_KEY $SESSION_TOKEN $@

exit 0