#!/bin/bash

#
# Usage:     
# $0 profile_from profile_to role_arn [session_name]
#

if [[ "$1" == "" || "$2" == "" || "$3" == "" ]]; then exit 1; fi

SESSION_NAME="$([[ "$4" != "" ]] && echo "$4" || echo "$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)")"
JSON_RESPONSE="$(aws --profile $1 sts assume-role --role-arn $3 --role-session-name $SESSION_NAME)"

if [ "$JSON_RESPONSE" == "" ]; then echo ""; exit 1; fi

AWS_ACCESS_KEY_ID="$(sed -e 's/^"//' -e 's/"$//' <<< "$(echo $JSON_RESPONSE | jq .Credentials.AccessKeyId)")"
AWS_SECRET_ACCESS_KEY="$(sed -e 's/^"//' -e 's/"$//' <<< "$(echo $JSON_RESPONSE | jq .Credentials.SecretAccessKey)")"
AWS_SESSION_TOKEN="$(sed -e 's/^"//' -e 's/"$//' <<< "$(echo $JSON_RESPONSE | jq .Credentials.SessionToken)")"

$HOME/bin/aws-profile $2 $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $AWS_SESSION_TOKEN