#!/bin/bash

#
# Usage:     
# $0 profile_name mfa_serial mfa_code
#

[[ "$#" -lt 3 ]] && exit 1

PROFILE_TO="$1" && shift
MFA_SERIAL="$1" && shift
MFA_CODE="$1" && shift

JSON_RESPONSE="$( aws sts get-session-token --serial-number $MFA_SERIAL --token-code $MFA_CODE )"

[[ "$JSON_RESPONSE" == "" ]] && echo "" && exit 1

ACCESS_KEY_ID="$( sed -e 's/^"//' -e 's/"$//' <<< "$( echo $JSON_RESPONSE | jq .Credentials.AccessKeyId )" )"
SECRET_ACCESS_KEY="$( sed -e 's/^"//' -e 's/"$//' <<< "$( echo $JSON_RESPONSE | jq .Credentials.SecretAccessKey )" )"
SESSION_TOKEN="$( sed -e 's/^"//' -e 's/"$//' <<< "$( echo $JSON_RESPONSE | jq .Credentials.SessionToken )" )"

$HOME/bin/aws-profile $PROFILE_TO $ACCESS_KEY_ID $SECRET_ACCESS_KEY $SESSION_TOKEN $@